### ISSUE TITLE
Kubernetes - GKE Monitoring metrics

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control-registry#188]
```yaml
metrics:
  type: prometheus
  labels: 
    cluster: abc
  
  queries:
    prometheus:
      node_cpu:
    gke: 
      node_cpu:
```
sum(rate(kubernetes_io:container_cpu_core_usage_time{container_name!="", cluster_name="hub-cluster"}[5m])) by (metadata_system_node_name) |  
-- | --
sum(kubernetes_io:container_memory_used_bytes{cluster_name="hub-cluster"}) by (metadata_system_node_name) |  
  |  
sum(rate(kubernetes_io:container_cpu_core_usage_time{container_name!="", cluster_name="hub-cluster"}[5m])) by (pod_name) |  
sum(kubernetes_io:container_memory_used_bytes{container_name!="",cluster_name="hub-cluster"}) by (pod_name) |  
sum(rate(kubernetes_io:container_cpu_core_usage_time{container_name!="", cluster_name="hub-cluster"}[5m])) by (namespace_name) |  
sum(kubernetes_io:container_memory_used_bytes{container_name!="",cluster_name="hub-cluster"}) by (namespace_name) |
